# Generated by Django 4.1 on 2022-11-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('post_pic', models.ImageField(upload_to='post_pics')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
