# Generated by Django 4.1 on 2022-11-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(upload_to='post_pics/'),
        ),
    ]
