# Generated by Django 4.1 on 2022-11-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
