# Generated by Django 4.1 on 2022-11-06 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0005_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calorie_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 9, 25, 24, 912358, tzinfo=datetime.timezone.utc)),
        ),
    ]
