# Generated by Django 4.1 on 2022-11-06 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0006_post_calorie_count_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 9, 50, 25, 369353, tzinfo=datetime.timezone.utc)),
        ),
    ]
