# Generated by Django 4.1 on 2022-11-06 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_remove_post_calorie_count_post_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calorie_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 10, 0, 55, 479061, tzinfo=datetime.timezone.utc)),
        ),
    ]
