# Generated by Django 4.1 on 2022-11-06 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0009_post_calorie_count_alter_post_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='food_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 10, 8, 23, 367197, tzinfo=datetime.timezone.utc)),
        ),
    ]
