# Generated by Django 4.1 on 2022-11-06 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0010_remove_post_food_name_alter_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 10, 11, 55, 719509, tzinfo=datetime.timezone.utc)),
        ),
    ]
