# Generated by Django 4.1 on 2022-11-06 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_post_food_name_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 19, 3, 19, 173016, tzinfo=datetime.timezone.utc)),
        ),
    ]
